### ISSUE TITLE
Add support of AWS SQS

### ISSUE THREAD

**Issue by runningman84** [sensu/sensu-transport#22]
It would be great if we could replace RabbitMQ with SQS. This would be cheaper and easier to maintain...

**Comment by jcmartins** [comment]
+1

**Comment by runningman84** [comment]
This should be already possible with some limitations:
https://www.simple.com/engineering/scaling-sensu-by-doing-less

**Comment by cwjohnston** [comment]
Simple has published their SQS transport on github: https://github.com/SimpleFinance/sensu-transport-snssqs
