### ISSUE TITLE
Add support for using a Redis "namespace" option to the Redis library

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-transport#28]
Source: https://github.com/sensu/sensu/issues/1014

**Comment by portertech** [comment]
@calebhailey going to close this one, as Sensu already uses its own keyspace for transport related data. We want to keep the keyspace consistent across installs/deployments for debugging purposes. One less nob to turn.

**Comment by calebhailey** [comment]
@portertech :+1:
