### ISSUE TITLE
Check results silently dropped when the transport is down

### ISSUE THREAD

**Issue by moises-silva** [sensu/sensu-transport#32]
No logging feedback (or any kind of feedback) is provided by the client socket interface (client/socket.rb) when a check is sent (e.g echo '{check data} | nc localhost 3030') and the transport is down (e.g reconnecting). The sensu client will reply with 'ok', so there's not even a chance we can retry later or even log on our side that something went wrong.

See also PR sensu/sensu#1352 as a use case where this issue prevents replying with a negative response to the HTTP request.

**Comment by moises-silva** [comment]
Created PR #33 which fixes this issue

**Comment by portertech** [comment]
Merged https://github.com/sensu/sensu-transport/pull/33
