### ISSUE TITLE
Support for Kafka

### ISSUE THREAD

**Issue by misham** [sensu/sensu-transport#40]
I'm interested in adding support for Kafka to have parity with RabbitMQ features.  I'm planning on taking a similar approach to https://github.com/SimpleFinance/sensu-transport-snssqs

Wondering if this is something that's been tried before and/or if there are any concerns around this?

Thank you

**Comment by portertech** [comment]
@misham I don't believe anyone has tackled using Kafka as a transport, beyond creating an empty repository ;) Sorry for not responding to this issue, I hope you are still interested in this problem! 

Using a similar approach as Simple's SNSSQS Transport does limit what the transport has to do, known constraints (i.e. no pubsub checks).

I like the look of this Kafka library, async publishing https://github.com/zendesk/ruby-kafka#asynchronously-producing-messages :+1:

**Comment by hvyas** [comment]
Hi @misham: Did you attempt to create Kafka transport? Would appreciate if you could share some updates/experience with it..

**Comment by misham** [comment]
@hvyas we decided to not use Sensu, so stopped all work on it.

**Comment by hvyas** [comment]
Thanks for your response!
