### ISSUE TITLE
Feature request: Amazon MQ support

### ISSUE THREAD

**Issue by kdegraaf** [sensu/sensu-transport#59]
It would be great if Sensu could use Amazon MQ (which, as of this writing, means Apache ActiveMQ 5.15.0) as a transport.

Just as Sensu's support for ElastiCache means we don't have to manage Redis ourselves, support for Amazon MQ would mean we don't have to manage RabbitMQ ourselves.  This would lighten the footprint and undifferentiated heavy lifting of AWS Sensu deployments.

In the meantime, I'll likely be using the third-party SNS/SQS transport.

Thanks.

**Comment by obfuscurity** [comment]
@kdegraaf To address my own curiosity, could you comment on why you closed this issue?

**Comment by lfernandezpricco** [comment]
@kdegraaf same question here. It doesn't seem to have incorporated support for Amazon MQ as a transport option, why is this closed?
