### ISSUE TITLE
RabbitMQ use a separate connection for publish and subscribe

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-transport#61]
RabbitMQ alarms and throttling is applied at the connection (and channel) level. Currently, we suspect this causes the sensu-server RabbitMQ consumers to lock up along with the publishers (really bad). In order to completely separate the consumers from the publishers, separate connections (and channels) must be used.

**Comment by annaplotkin** [comment]
We want to get an unstable Enterprise build over to folks to test.
