### ISSUE TITLE
Replace amqp gem with bunny

### ISSUE THREAD

**Issue by mdrozdo** [sensu/sensu-transport#63]
Referring to issues in amqp gem with validation of server hostname and certificates (https://github.com/sensu/sensu/issues/1310), @michaelklishin strongly suggested that sensu should migrate to https://github.com/ruby-amqp/bunny. 

I found an experimental branch at https://github.com/sensu/sensu-transport/compare/experiment/remove-em in which @portertech seems to have solved it. Is that code working? Would it be possible to push this change forward, or at least bring it to a point where it could be used in production?

I'd gladly help but I have close to zero experience with Ruby. We could definitely help out with testing the solution, though.

**Comment by annaplotkin** [comment]
Thanks for raising this! We have tried this in the past and it has not been considered ideal or feasible (which is why this was never merged). As such, I'm going to close this issue. We will investigate and address the client validation concerns in Sensu Go.
